---
- name: Check if required CLI tools are installed
  block:
    - name: Check for jq
      command: "jq --version"
      register: jq_installed
      changed_when: false
      failed_when: false
    - name: Check for OpenShift CLI (oc)
      command: "oc version"
      register: oc_installed
      changed_when: false
      failed_when: false
  rescue:
    - fail:
        msg: "Required CLI tools (jq and oc) are not installed."
- name: Include vars.yaml if tag is gitlab_configuration
  ansible.builtin.include_vars:
    file: vars.yaml
  tags: gitlab_configuration
- name: Get GitLab Ingress
  k8s_info:
    api_version: networking.k8s.io/v1
    kind: Ingress
    namespace: "{{ gitlab_namespace }}"
    label_selectors:
      - app=webservice
  register: ingress_info
  tags: gitlab_configuration
- name: Set GitLab API URL fact
  set_fact:
    api_url: "https://{{ ingress_info.resources[0].spec.rules[0].host }}/"
  tags: gitlab_configuration
- name: Get GitLab initial root password secret
  k8s:
    state: present
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: gitlab-gitlab-initial-root-password
        namespace: gitlab-system
  register: gitlab_secret
  tags: gitlab_configuration
- name: Decode GitLab initial root password
  set_fact:
    api_password: "{{ gitlab_secret.result.data.password | b64decode }}"
    api_username: root
  tags: gitlab_configuration
- name: Print GitLab initial root password
  debug:
    msg: "GitLab initial root password is: {{ api_password }}"
  tags: gitlab_configuration
- name: Create GitLab groups
  community.general.gitlab_group:
    name: "{{ item }}"
    state: present
    visibility: public
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
  loop: "{{ gitlab_users | map(attribute='group') | unique }}"
  tags: gitlab_configuration
- name: Create GitLab users
  community.general.gitlab_user:
    name: "{{ item.name }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email }}"
    group: "{{ item.group }}"
    state: present
    sshkey_file: "{{ item.sshkey_file | default(omit)}}"
    isadmin: "{{ item.isadmin | default(omit)}}"
    confirm: false
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
  loop: "{{ gitlab_users }}"
  tags: gitlab_configuration
- name: Add a user to a GitLab Group
  community.general.gitlab_group_members:
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
    gitlab_group: "{{ item.group }}"
    gitlab_user: "{{ item.username }}"
    access_level: "{{ item.access }}"
    state: present
  loop: "{{ gitlab_users }}"
  tags: gitlab_configuration
- name: Create GitLab repository
  community.general.gitlab_project:
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
    name: sample-app
    group: team-a
    visibility: public
    state: present
    default_branch: main
    initialize_with_readme: true
  tags: gitlab_configuration

# - name: Clone repository over HTTPS
#   ansible.builtin.git:
#     repo: "{{ api_url }}/team-a/sample-app.git"
#     dest: /tmp/sample-app
#     clone: yes
#     force: yes
#     version: main
#     accept_hostkey: yes
# - name: Copy files to repository
#   copy:
#     src: "{{ item }}"
#     dest: /tmp/sample-app/
#   loop:
#     - catalog-info.yaml
#     - users-groups.yaml
# - name: Add files to GitLab repository
#   git:
#     repo: /tmp/sample-app
#     dest: "{{ gitlab_url }}/team-a/sample-app.git"
#     push: yes
#     force: yes
#     remote: origin
#     version: main
#     force: yes
