---
- hosts: localhost
  gather_facts: no
  vars_files: vars.yaml
  tasks:
  - name: install pre-requisites
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes
        - python-gitlab==1.15.0
  - name: Install cert-manager operator
    community.okd.k8s:
      state: present
      src: "{{ path_playbooks }}/lab-prep/cert-manager-operator.yaml"
  - name: wait until cert-manager is created
    ansible.builtin.pause:
      seconds: 2
  - name: Install Gitlab
    ansible.builtin.include_tasks:
      file: gitlab_install.yaml
  - name: Setup GitLab with some initial configuration
    ansible.builtin.include_tasks:
      file: gitlab_configuration.yaml
    tags: gitlab_conf
  - name: Install Red Hat Developer Hub
    ansible.builtin.include_tasks:
      file: rhdh_install.yaml
  - name: Configure Red Hat Developer Hub
    ansible.builtin.include_tasks:
      file: rhdh_configuration.yaml
