---
- hosts: localhost
  gather_facts: no
  vars_files: vars.yaml
  tasks:
  - name: install pre-requisites
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes
        - python-gitlab==1.15.0
  - name: Install certmanager
    ansible.builtin.include_tasks:
      file: certmanager_install.yml
  - name: Install Gitlab
    ansible.builtin.include_tasks:
      file: gitlab_install.yml
  - name: Setup GitLab with some initial configuration
    ansible.builtin.include_tasks:
      file: gitlab_configuration.yml
    tags: gitlab_configuration
  - name: Install Red Hat Developer Hub
    ansible.builtin.include_tasks:
      file: rhdh_install.yml
  - name: Configure Red Hat Developer Hub
    ansible.builtin.include_tasks:
      file: rhdh_configuration.yml
    tags: rhdh_configuration
