apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh-gitlab
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
      - name: app-config-rhdh      
    extraFiles:
      mountPath: /opt/app-root/src
    extraEnvs:
      secrets:
        - name: rhdh-secrets      
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
